export const REGISTRATION_FETCHED = 'registration.REGISTRATION_FETCHED';
export const LOGIN_UPDATED = 'registration.LOGIN_UPDATED';
export const PASSWORD_UPDATED = 'registration.PASSWORD_UPDATED';
export const REGISTRATION_DATA_SUBMITTED = 'registration.REGISTRATION_DATA_SUBMITTED';