server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CLOUDSYSTEMHQ
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  output:
    ansi:
      enabled: always
security:
  oauth2:
    resource:
      filter-order: 3