server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CLOUDSYSTEMHQ
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  output:
    ansi:
      enabled: always
security:
  oauth2:
    resource:
      filter-order: 3

smsprovider:
  providerUri: http://cp.smsp.by
  user: laggger222@gmail.com
  timeout: 15
  senderName: Konsultant
  api:
    key: i834282812
    accountInfoUri: api/user_balance
    msgSendUri: api/msg_send
    msgListUri: api/msg_list

otpprovider:
  providerUri: https://textbelt.com/
  otpLifetime: 120
  api:
    key: textbelt
    sendOtpUri: otp/generate
    verifyOtpUri: otp/verify